### ISSUE TITLE
Compiling failed

### ISSUE THREAD

**Issue by HombreBigClown** [bigclownlabs/bcp-sigfox-motion-detector#2]
bcf-sigfox-motion-detector$ make
Clean output ...
Compiling: app/application.c
app/application.c: In function 'application_init':
app/application.c:297:5: error: too many arguments to function 'bc_module_battery_init'
     bc_module_battery_init(BC_MODULE_BATTERY_FORMAT_MINI);
     ^~~~~~~~~~~~~~~~~~~~~~
In file included from sdk/bcl/inc/bcl.h:47:0,
                 from app/application.h:8,
                 from app/application.c:1:
sdk/bcl/inc/bc_module_battery.h:45:6: note: declared here
 void bc_module_battery_init(void);
      ^~~~~~~~~~~~~~~~~~~~~~
sdk/Makefile.mk:340: recipe for target 'obj/debug/app/application.o' failed
make[1]: *** [obj/debug/app/application.o] Error 1
sdk/Makefile.mk:171: recipe for target 'debug' failed
make: *** [debug] Error 2

Is need to remove: BC_MODULE_BATTERY_FORMAT_MINI

**Comment by hubmartin** [comment]
Thank you, the battery module is now auto-detected.
Fixed
